### ISSUE TITLE
Line number logging with __LINE__ doesn't work

### ISSUE THREAD

**Issue by c42f** [c42f/MicroLogging.jl#1]
As pointed out by @quinnj, `@__LINE__` doesn't do what a C programmer naively expects :-/
https://github.com/c42f/MicroLogging.jl/commit/f6db3715c681af90511f5219252f16e57096a194#commitcomment-20846418

This could come from a backtrace instead, it just seems a bit excessive to invoke one to get something that could/should be inlined at the call site.

**Comment by quinnj** [comment]
For reference, I copped out by just requiring the line number as an input to the macro; see [here](https://github.com/JuliaWeb/HTTP.jl/blob/15f33bc518902b29fdb132f4bcc696fe3aa37ecc/src/utils.jl#L45)

**Comment by c42f** [comment]
Ah, that's a pity!  Thanks for the xref :-)

@ihnorton has a scary looking hack that gives better results here
https://github.com/JuliaLang/julia/issues/8066#issuecomment-127471401

but it still doesn't do quite the right thing.

**Comment by c42f** [comment]
Another related issue https://github.com/JuliaLang/julia/issues/9577
Perhaps there's just no solution to this at this stage.

**Comment by c42f** [comment]
This is solved in 0.7 thanks to https://github.com/JuliaLang/julia/pull/21746

There is no, and will be no solution to this before 0.7 is released, by the looks of things.

**Comment by c42f** [comment]
Related PR to make this easier with Jameson's new code in 0.7 - https://github.com/JuliaLang/julia/pull/22623
