### ISSUE TITLE
Logging errors under 32-bit Julia

### ISSUE THREAD

**Issue by tshort** [c42f/MicroLogging.jl#12]
When I try to log status of variables, I get errors like that shown below. This is with 32-bit Julia under Linux.

```julia
julia> using MicroLogging

julia> @debug "hello"

julia> @info "hello"
julia> a=9
9

julia> @info "hello" a
I-  hello                                                                                                        Info REPL[20]:1
E-  Exception while generating log record in module Main at REPL[20]:1                                          Error REPL[20]:1
Exception handling log message: BoundsError(9, 2)
  module=Main  file=REPL[20]  line=1
  Second exception: MethodError(start, (BoundsError(9, 2),), 0x00005d20)
```

There's a `try` in `dispatch_messenger` that I commented out. With that, I get the following error. That's as far as I made it tonight.

```julia
julia> a=8
8

julia> @info "hello" a
I-  hello                                                                                                         Info REPL[3]:1
ERROR: BoundsError: attempt to access 8
  at index [2]
Stacktrace:
 [1] indexed_next(::Int32, ::Int32, ::Bool) at ./tuple.jl:60
 [2] #display_message#7(::Void, ::Void, ::Any, ::Function, ::InteractiveLogger, ::Any, ::String, ::Any, ::Any, ::Symbol, ::String, ::Any) at /home/tshort/.julia/v0.7/MicroLogging/src/loggers.jl:209
 [3] dispatch_message(::InteractiveLogger, ::LogLevel, ::Module, ::Symbol, ::Symbol, ::String, ::Int32, ::getfield(, Symbol("##9#cm#1")){Int32}) at /home/tshort/.julia/v0.7/MicroLogging/src/core.jl:336
 [4] top-level scope at /home/tshort/.julia/v0.7/MicroLogging/src/core.jl:320
```

**Comment by c42f** [comment]
Thanks for the report, this is a bit of an oddity. Which build is this? Is it the official 32 bit build of julia-0.6?

**Comment by tshort** [comment]
It's the 32-bit nightly build on Linux. I'll try to dig a little deeper over the weekend.

**Comment by c42f** [comment]
Actually this is the problem addressed by 7f5e280, I just didn't recognize the obscure looking error message.  Should be fixed on master.

**Comment by tshort** [comment]
Thanks, Chris. Works now! I'm looking forward to having MicroLogging in Base. It's a nice design, and I like how the output looks.

**Comment by c42f** [comment]
The most important core parts were merged yesterday which is pretty exciting.  Dealing with fallout now :) https://github.com/JuliaLang/julia/issues/25109
