### ISSUE TITLE
String interpolation fails

### ISSUE THREAD

**Issue by KristofferC** [c42f/MicroLogging.jl#4]
```
julia> @info md"# Simple progress logging"
ERROR: ArgumentError: Argument to @closure must be a closure!
```

**Comment by c42f** [comment]
Huh, this is a particularly obscure error, but the underlying reason is that you need `using Base.Markdown` before you use the `md` string macro.

**Comment by KristofferC** [comment]
Oh, woops! :D

**Comment by c42f** [comment]
The problem is in `FastClosures`, where I call `macroexpand` inside a macro to do some dirty lowering tricks, but if the result is an error, the error message is very confusing.

**Comment by c42f** [comment]
Should be fixed now in FastClosures.
