### ISSUE TITLE
Register?

### ISSUE THREAD

**Issue by quinnj** [c42f/MicroLogging.jl#6]
I'm eager to incorporate this into HTTP.jl. Would you be willing to register? I certainly understand some of the 0.6 issues right now, but I think it'd still be worth it to help test things out in different contexts.

**Comment by c42f** [comment]
Yes, I need to register this, I think it's about at the stage where I need more feedback.

There's still a bunch of known design issues - see #5.

**Comment by c42f** [comment]
Ok, I've taken the plunge!

https://github.com/JuliaLang/METADATA.jl/pull/11021

**Comment by c42f** [comment]
This is now registered.  I also put some work into making the dependency `FastClosures` work again on 0.7.

You'll find there's some parts which still need a lot of polish.  In particular the default `SimpleLogger` was started as a prototyping playground.  It's probably ok for interactive use in the REPL, but it's not much good for production.  Luckily it's pretty easy to write and inject your own logger.
